<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Shop Now</name>
   <tag></tag>
   <elementGuidId>fb287f34-f585-4815-b44b-a575a76d738e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='miceLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#miceLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>17673212-5d95-459b-af15-1b8a7c283946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>miceLink</value>
      <webElementGuid>cac432a5-8e91-4bd0-a184-5ab053961544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub roboto-regular ng-scope</value>
      <webElementGuid>fca32529-3cac-4b04-92f2-c88fbe52e428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Shop_Now</value>
      <webElementGuid>623c6b5c-90b5-4433-a4e0-69eb4faee6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop Now</value>
      <webElementGuid>80f00cc5-dcd4-41a4-a2e7-cdbeb5161976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;miceLink&quot;)</value>
      <webElementGuid>63130393-a334-4b56-ba28-3e765cf2a7bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='miceLink']</value>
      <webElementGuid>4eb5fa9d-820f-476b-aaa4-7c41741d39f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='miceImg']/div/label</value>
      <webElementGuid>48fe50c7-a16d-4c06-bef2-ceb518d8c9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MICE'])[1]/following::label[1]</value>
      <webElementGuid>7b0d1745-b074-44dc-a9a1-b7b41212b13b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[3]/following::label[1]</value>
      <webElementGuid>305902b2-3401-4bb2-b163-d51cda71bc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HEADPHONES'])[1]/preceding::label[1]</value>
      <webElementGuid>672a72f6-9f06-425e-a80c-a9d86e668697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop Now'])[5]/preceding::label[1]</value>
      <webElementGuid>e1f704f8-5dc1-456c-81ae-901d7ab76c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/label</value>
      <webElementGuid>7ac0fc34-cfb7-4ead-89ec-584d462e144f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'miceLink' and (text() = 'Shop Now' or . = 'Shop Now')]</value>
      <webElementGuid>15396394-ee5c-4f92-af51-f796551c8bef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
