<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_TotalCartPrice</name>
   <tag></tag>
   <elementGuidId>7240d103-ea3d-4c4f-8cc7-f4e2b3ceaf15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shoppingCart']/table/tfoot/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>193093aa-2c2d-4d32-96f7-d708e1cc37b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>eeebc74d-ceb3-4936-9f3b-73b9ec435346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        TOTAL:
                        $59.98
                    </value>
      <webElementGuid>79dc4c19-6614-4791-8cfe-fcb57fe01e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCart&quot;)/table[@class=&quot;fixedTableEdgeCompatibility&quot;]/tfoot[1]/tr[1]/td[2]</value>
      <webElementGuid>837220f9-70c6-4595-bb63-54b0b38950cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr/td[2]</value>
      <webElementGuid>ac1f631b-4476-4a64-b3a4-66b71d7b2e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAYMENT OPTIONS:'])[1]/following::td[1]</value>
      <webElementGuid>fa136a9d-e270-43ad-a00e-66a2ce229873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMOVE'])[1]/following::td[2]</value>
      <webElementGuid>d66274af-1729-48b9-bd68-5c5382e8874e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr/td[2]</value>
      <webElementGuid>4ae9e9b4-b8d8-4754-9834-36a5950dfc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                        TOTAL:
                        $59.98
                    ' or . = '
                        TOTAL:
                        $59.98
                    ')]</value>
      <webElementGuid>72c2266f-5bc0-4ef2-9653-114cce678921</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
