<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_GRAY</name>
   <tag></tag>
   <elementGuidId>3e16abfd-a2dc-4928-bfbf-07a1d0ef68d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//tr[@id='product']/td[2]/a/label[2]/span)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2ae5b275-eacd-487d-a129-c0a989c72ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>a81b9f71-1ba2-480b-b9d5-5fb419d3c92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GRAY</value>
      <webElementGuid>02a5ce3c-b76f-44bf-a639-72b93e0637bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userCart&quot;)/tool-tip-cart[@id=&quot;toolTipCart&quot;]/div[1]/table[1]/tbody[1]/tr[@id=&quot;product&quot;]/td[2]/a[1]/label[@class=&quot;ng-binding&quot;]/span[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>221274c1-7f0d-42f6-af87-3b822bb01c4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='product']/td[2]/a/label[2]/span)[2]</value>
      <webElementGuid>f555d9d5-1d87-4209-8ac7-4722d77791ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY: 2'])[2]/following::span[1]</value>
      <webElementGuid>404a5113-6a36-4f55-b93d-e90d5797b209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(2 Items)'])[2]/preceding::span[1]</value>
      <webElementGuid>bfbe403e-a339-495c-abdd-a1b82dff284d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/tool-tip-cart/div/table/tbody/tr/td[2]/a/label[2]/span</value>
      <webElementGuid>2e08c3ce-0abd-4ebe-b1e4-f4d6ad5dcc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'GRAY' or . = 'GRAY')]</value>
      <webElementGuid>9def3e12-b2ce-4e74-83dc-51bf3e537638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
