<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Address</name>
   <tag></tag>
   <elementGuidId>bd998f16-971d-4a33-aeee-7859d79b6c8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userDetails']/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>df09c5f6-8bc0-4c49-b7d8-319a0c41e492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-show</name>
      <type>Main</type>
      <value>user.address != ''</value>
      <webElementGuid>1652456b-06af-4fe1-b479-79d26fb656fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>63d54519-aba1-431e-a08f-7f6352ab2182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Bumi Ayu Gg. Pungut Sari No.6, Sanur</value>
      <webElementGuid>91bf9759-d29c-4623-b9c3-3cb3c7e626fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetails&quot;)/div[2]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>7a1fdfc9-4e6b-4c61-8546-c7547f90dcf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userDetails']/div[2]/label</value>
      <webElementGuid>da47c0e1-7eab-48f7-958e-ab7407ebe51c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Belaka'])[1]/following::label[1]</value>
      <webElementGuid>45f554a0-94ea-45a2-b46a-3b48f39baaae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER PAYMENT'])[2]/following::label[4]</value>
      <webElementGuid>004c93a0-5cf1-4326-af80-1d14752de142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Denpasar'])[1]/preceding::label[1]</value>
      <webElementGuid>1249e97d-f4f7-47f6-a2c6-681529b7b28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/preceding::label[2]</value>
      <webElementGuid>9f7eb4af-3979-4dd6-99e6-bea869a9f88a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label</value>
      <webElementGuid>16a9b5ef-45ef-46a3-9aaa-accb1f784e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Jl. Bumi Ayu Gg. Pungut Sari No.6, Sanur' or . = 'Jl. Bumi Ayu Gg. Pungut Sari No.6, Sanur')]</value>
      <webElementGuid>71741b5d-f6ba-4837-addd-6547dc57286a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
