<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_userDetails</name>
   <tag></tag>
   <elementGuidId>7bbc6bfe-e8ae-4569-98ef-3e04246d86c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userDetails']/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userDetails > div > label.ng-binding</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a5b87ff3-2c46-4bf7-a64f-13e1aa9e95fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>89e81e88-e740-458d-a4dc-a02256001558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Belaka</value>
      <webElementGuid>63479e03-a8e0-4a86-b603-629a61523cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDetails&quot;)/div[1]/label[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>e6bfa1c3-a60b-42f1-8042-16084f425340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userDetails']/div/label</value>
      <webElementGuid>3dd83d75-2a09-4a12-a75e-92c090b212d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER PAYMENT'])[2]/following::label[3]</value>
      <webElementGuid>a31c435d-f9fd-4e38-81a1-ac32c446ddb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORDER PAYMENT'])[1]/following::label[3]</value>
      <webElementGuid>c10c4584-001c-4a68-ad45-5fe53fcab706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jl. Bumi Ayu Gg. Pungut Sari No.6, Sanur'])[1]/preceding::label[1]</value>
      <webElementGuid>d39878d2-b23e-4883-8092-d9801484b4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota Denpasar'])[1]/preceding::label[2]</value>
      <webElementGuid>ab285867-fe98-47f9-b7eb-5e655028e64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/label</value>
      <webElementGuid>a491d4aa-d6b6-4d55-86cb-461b3c441369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Test Belaka' or . = 'Test Belaka')]</value>
      <webElementGuid>e4f94397-d80e-4e32-a7fb-8a3650a2fab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
